$(document).ready(function() {var formatter = new CucumberHTML.DOMFormatter($('.cucumber-report'));formatter.uri("file:src/test/resources/features/galatasaray/homescreen.feature");
formatter.feature({
  "name": "Home Screen Galatasaray",
  "description": "",
  "keyword": "Feature",
  "tags": [
    {
      "name": "@home"
    },
    {
      "name": "@severity\u003dnormal"
    }
  ]
});
formatter.background({
  "name": "",
  "description": "",
  "keyword": "Background"
});
formatter.before({
  "status": "passed"
});
formatter.step({
  "name": "I open the app",
  "keyword": "Given "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_open_the_app()"
});
formatter.result({
  "status": "passed"
});
formatter.scenario({
  "name": "verify user should not be able to register with wrong OTP",
  "description": "",
  "keyword": "Scenario",
  "tags": [
    {
      "name": "@home"
    },
    {
      "name": "@severity\u003dnormal"
    },
    {
      "name": "@home_4"
    }
  ]
});
formatter.step({
  "name": "I should see the autogenerated message",
  "keyword": "When "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_should_see_the_autogenerated_message()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I click on the \"Tabi ki isterim Hocam\" message card",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_click_on_the_message_card(java.lang.String)"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "message \"Tabi ki isterim Hocam\" should be sent",
  "keyword": "Then "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.message_should_be_sent(java.lang.String)"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I choose my favourite footballer",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_choose_my_favourite_footballer()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I enter firstName and lastName",
  "rows": [
    {}
  ],
  "keyword": "Then "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_enter_firstName_and_lastName(io.cucumber.datatable.DataTable)"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I click on next button",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_click_on_next_button()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I select gender as",
  "rows": [
    {}
  ],
  "keyword": "Then "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_select_gender_as(io.cucumber.datatable.DataTable)"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I click on next button",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_click_on_next_button()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I select my birthdate as",
  "rows": [
    {}
  ],
  "keyword": "Then "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_select_my_birthdate_as(io.cucumber.datatable.DataTable)"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I click on next button",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_click_on_next_button()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I accept the contract",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_accept_the_contract()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I enter valid phoneno",
  "keyword": "When "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_enter_valid_phoneno()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I click on next button",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_click_on_next_button()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I enter wrong OTP 2222",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_enter_wrong_OTP(java.lang.Integer)"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I click on next button",
  "keyword": "And "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_click_on_next_button()"
});
formatter.result({
  "status": "passed"
});
formatter.step({
  "name": "I should get wrong code try again message",
  "keyword": "Then "
});
formatter.match({
  "location": "galatasaray.stepdefinition.HomeScreenSteps.i_should_get_wrong_code_try_again_message()"
});
formatter.result({
  "status": "passed"
});
formatter.after({
  "status": "passed"
});
});